# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-08 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='incaResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wdate', models.CharField(blank=True, max_length=10, null=True)),
                ('itemcode', models.CharField(blank=True, max_length=20, null=True)),
                ('itemname', models.CharField(blank=True, max_length=100, null=True)),
                ('DNA_score', models.DecimalField(blank=True, decimal_places=12, max_digits=22, null=True)),
                ('DNA_index', models.DecimalField(blank=True, decimal_places=12, max_digits=22, null=True)),
                ('probability', models.DecimalField(blank=True, decimal_places=12, max_digits=22, null=True)),
                ('MAX_rate', models.IntegerField(default=0)),
                ('MIN_rate', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'time_series_1Y_inverse',
            },
        ),
    ]
