# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-08 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incatest', '0002_auto_20170508_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incaoutcomes',
            name='DNA_index',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='incaoutcomes',
            name='DNA_score',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='incaoutcomes',
            name='probability',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=22, null=True),
        ),
    ]
