# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incatest', '0002_auto_20170511_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='wdate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='end_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='start_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
