# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 03:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incatest', '0003_auto_20170511_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterVSInvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wdate', models.DateField(blank=True, null=True)),
                ('intervsinvest', models.DecimalField(blank=True, decimal_places=17, max_digits=30, null=True)),
                ('intervsinvest_index', models.DecimalField(blank=True, decimal_places=17, max_digits=30, null=True)),
                ('intervsinvest_score', models.DecimalField(blank=True, decimal_places=17, max_digits=30, null=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incatest.Result')),
            ],
        ),
    ]
