# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-08 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incatest', '0005_auto_20170508_0531'),
    ]

    operations = [
        migrations.CreateModel(
            name='incaPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemcode', models.CharField(blank=True, max_length=20, null=True)),
                ('wdate', models.CharField(blank=True, max_length=10, null=True)),
                ('open', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('close', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('trading_volume', models.IntegerField(default=0)),
                ('trading_value', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'stock_data',
            },
        ),
    ]
