# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incatest', '0006_auto_20170511_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='interest_index_score',
            field=models.DecimalField(blank=True, decimal_places=17, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='interest_index_score_sum',
            field=models.DecimalField(blank=True, decimal_places=17, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='intervsinvest_index_score_sum',
            field=models.DecimalField(blank=True, decimal_places=17, max_digits=30, null=True),
        ),
    ]
