# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-08 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incatest', '0006_incaprices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incaoutcomes',
            name='wdate',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='incaprices',
            name='wdate',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
