# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incatest', '0007_auto_20170515_1403'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fund',
            table=None,
        ),
    ]
