# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 08:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incatest', '0008_auto_20170516_0842'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fund',
            table='stock_itemcode',
        ),
    ]
