# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-08 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incatest', '0009_auto_20170508_0635'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='incaoutcomes',
            new_name='Outcome',
        ),
        migrations.RenameModel(
            old_name='incaPrices',
            new_name='Price',
        ),
    ]
