# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incatest', '0009_auto_20170516_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='index',
            field=models.DecimalField(blank=True, decimal_places=17, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='index_score',
            field=models.DecimalField(blank=True, decimal_places=17, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=17, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=17, default=10.0, max_digits=30, null=True),
        ),
    ]
