# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-08 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incatest', '0010_auto_20170508_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemcode', models.CharField(blank=True, max_length=20, null=True)),
                ('itemname', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
    ]
