# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-08 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incatest', '0012_auto_20170508_0756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fund',
            old_name='country',
            new_name='countryCode',
        ),
    ]
