# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-08 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incatest', '0013_auto_20170508_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(blank=True, null=True, upload_to='%Y/%m/%d')),
            ],
        ),
    ]
